### ISSUE TITLE
MoveToCart creates double entries for a product

### ISSUE THREAD

**Issue by nfunwigabga** [hassansin/dbcart#15]
Nice package.
May be nice to change the `moveToCart(Cart $cart)` method to check if any of the products in the source cart already exists in the receiving cart. At the moment, it copies the products from cart A to cart B, even if the products are already in cartB. Maybe something like this:

```php
public function moveToCart(Cart $cart)
{
    $current_items = $cart->items()->pluck('product_id');
    $items_to_update = $this->items()->whereNotIn('product_id', $current_items);
    $items_to_update->update([
        'cart_id' => $cart->id 
    ]);
    $cart->item_count = $cart->items()->sum('quantity');
     ....
}
```

**Comment by hassansin** [comment]
Thanks for using the package. Please try again from master branch.
