### ISSUE TITLE
Argument 1 passed to Illuminate\Database\Eloquent\Model::update() must be of the type array

### ISSUE THREAD

**Issue by frismedia** [hassansin/dbcart#5]
The Cart model methods 'expire' and 'complete' call the update method with 2 strings as arguments instead of the expected first argument of an array.

Maybe this is something changed in one of the versions of Laravel, but I'm using the latest and in that version this error exists.

**Comment by hassansin** [comment]
Thanks for opening the issue. I'll look into this soon.
