### ISSUE TITLE
Cart total / value > 1000 / wrong number_format

### ISSUE THREAD

**Issue by bd8** [hassansin/dbcart#6]
Hi,

if the cart total amount is > 1000 it comes to an error.

"General error: 1366 Incorrect decimal value"

It formates the nummer like 1,000.00. I think that is wrong.

Mayby is a laravel configuration, I don´t know.

Thanks

**Comment by bd8** [comment]
Have changed this in the cart class:

Line 88 - 90

`    
public function setTotalPriceAttribute($value){
        $this->attributes['total_price'] = number_format($value, 2,'.','') > 0 ? number_format($value, 2,'.','') : 0;
    }`

no it works.

**Comment by hassansin** [comment]
Thanks for reporting the issue. I've removed number_format. I realized formatting should be done on the user side.
